# 워크플로 이름
name: CI

# 워크플로 트리거 조건
on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # vx.x.x로 시작하는 태그 푸시 시 실행
  pull_request: # PR 생성 또는 업데이트 시 실행

# 작업(Job) 정의
jobs:
  # 테스트 작업
  test:
    runs-on: ubuntu-latest # 실행 환경: 최신 Ubuntu
    steps:
      # GitHub 저장소 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js 설치 및 npm 캐싱
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # 의존성 설치
      - name: Install dependencies
        run: npm install

      # 테스트 실행
      - name: Run tests
        run: npm test

      # 코드 커버리지 확인
      - name: Run coverage
        run: npm run test:coverage

  # 빌드 및 배포 작업
  build:
    # test 작업 완료 후 실행
    needs: test
    runs-on: ubuntu-latest
    steps:
      # GitHub 저장소 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js 설치 및 npm 캐싱
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # 의존성 설치
      - name: Install dependencies
        run: npm install

      # 프로젝트 빌드
      - name: Build the project
        run: npm run build

      # npm에 패키지 배포
      - name: Publish to npm
        if: github.ref_type == 'tag' # 태그 푸시 시 실행
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # NPM 인증 토큰
